### ISSUE TITLE
transform ledger account names into legal beancount names

### ISSUE THREAD

**Issue by tbm** [zacchiro/ledger2beancount#33]
ledger2beancount offers an account mapping but it would be good to offer regex too, for example to replace all withspace with dashes.

**Comment by tbm** [comment]
After looking into this, I think storing these s/regexes in a config file requires a lot of work because we have to make sure they are safe.

Since we know what kind of transformations we have to make to end up with a valid account names, let's just do them automatically.  If users don't like the generated names, they can use the account map.

**Comment by zacchiro** [comment]
OK, this is fine (and indeed I've just merged #34).
Just an extra thought on the topic: beancount also insists that you have exactly 5 top-level account names, and forces them to be Assets/Equity/etc., while ledger doesn't care. There is no need to explicit supporting this, because we already have account map. I'm mentioning it here in case you want to add this to the doc --- I'm fine either way.
