### ISSUE TITLE
move the bulk of documentation away from top-level README

### ISSUE THREAD

**Issue by zacchiro** [zacchiro/ledger2beancount#83]
there's too much stuff in the top-level README, we should move most of the documentation to a separate file, and leave in the top-level README only (and preferably in this order):

1. overview
2. usage, i.e.:
  - CLI invocation
  - configuration file location
  - pointer to separate doc file for more info
3. dependencies
4. authors
5. license

As all that remains would be the current features section, the separate doc file should probably be named `doc/features.md`.

**Comment by tbm** [comment]
Yeah, I actually completed that work earlier today.

I'm actually not sure about keeping dependencies in the README.  I left (some of) it there because you mentioned deps in our IRC conversation but we could move it.  But it's shorter now so I guess it's ok.

Since the script works without a config file now, I moved all of the config stuff to the manual.  I also mention some of the key options there.

**Comment by tbm** [comment]
Oh, I called it `manual.md` after all because it has more than just the features.

I know there's some duplication between README and the manual but I think that's fine.  The manual should be standalone mostly.

**Comment by tbm** [comment]
Oh, I should warn you.  I went a little bit crazy writing an example file, but I think it will be really useful for ledger people who are new to beancount.

**Comment by zacchiro** [comment]
Ack on `doc/manual.md`.

Regarding dependencies, my keeping them in README is:
1) for many people it is still one of the decision point on whether to adopt a piece of software;
2) it's pretty short so it's not a hindrance in a file that should be short.
YMMV
